name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    strategy:
      matrix:
        ruby:
          - '3.0'
          - '3.1'
          - '3.2'
        gemfile:
          - Gemfile
          - gemfiles/activesupport-6.0.gemfile
          - gemfiles/activesupport-6.1.gemfile
          - gemfiles/activesupport-7.0.gemfile

    name: Ruby ${{ matrix.ruby }} ${{ matrix.gemfile }}
    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run tests
        run: |
          bundle exec rake
