name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    strategy:
      matrix:
        ruby:
          - '3.1'
          - '3.2'
          - '3.3'
        gemfile:
          - Gemfile
          - gemfiles/rails-7.0.gemfile
          - gemfiles/rails-7.1.gemfile
          - gemfiles/rails-edge.gemfile
        exclude:
          - ruby: '3.1'
            gemfile: gemfiles/rails-edge.gemfile
          - ruby: '3.2'
            gemfile: gemfiles/rails-edge.gemfile

    name: Ruby ${{ matrix.ruby }} ${{ matrix.gemfile }}
    steps:
      - uses: actions/checkout@50fbc622fc4ef5163becd7fab6573eac35f8462e # v1.2.0
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@bb6434c747fa7022e12fa1cae2a0951fcffcff26 # v1.253.0
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run tests
        run: |
          bundle exec rake
